### ISSUE TITLE
Convert to reusable action

### ISSUE THREAD

**Issue by alainamstutz** [opensafely-actions/.github#8]
I'd like to convert my study into a reusable action. My study is in this repo:

https://github.com/alainamstutz/diabetes-algo 

We had some people outside opensafely reviewing the algorithm code, hence, I used a personal repo in my own GitHub - but it's based on the opensafely template. And has also been reviewed by Tom Palmer who was involved in previous reusable actions. 

If needed I can open a new repo in opensafely org and copy-paste everything there, if that's easier/cleaner from your side.

Thanks!
Best,
-Alain

**Comment by iaindillingham** [comment]
Hello @alainamstutz 👋🏻 Thank you for developing a reusable action! Before I move it to the opensafely-actions organisation, I have a request and a suggestion.

First, the **request**. Could you please also allow a user to supply a dataset as a `.csv.gz` file and, optionally, as an `.arrow` file? Writing a dataset as an uncompressed `.csv` file can result in a very large file, and we have a limited amount of storage on Level 3. Whilst it is possible for a user to write a dataset as an uncompressed `.csv` file, we'd prefer datasets to be written as compressed `.csv.gz` files or as binary `.arrow` files.

If it is already possible for a user to supply a dataset in these formats, then please could you document?

Second, the **suggestion**. You've elected to pass configuration to the reusable action through options. It's also possible to pass configuration through the `config` property. Users may find it less fiddly to pass configuration through the `config` property than through options. Compare the following example to that given in the reusable action's `README.md`:

```yaml
diabetes_algo:
  run: diabetes-algo:[version]
  config:
    birth_date: your_dob_date_variable
    tmp_t1dm_ctv3_date: your_t2dm_from_primcare_date_variable
    tmp_max_hba1c_mmol_mol_num: your_max_hba1c_num_variable
    df_output: data_processed.rds
```

You may be wondering how you should get at the configuration, if it is passed through the `config` property. Well, it appears as a JSON-encoded string that's passed as the `--config` option. This option is passed automatically; you need not _pass_ it, although you will need to _parse_ it (i.e. the JSON-encoded string) into some other data structure.

We pass configuration through the `config` property in the [deciles-charts][] reusable action. You can find out more in `analysis/deciles_charts.py`.

[deciles-charts]: https://github.com/opensafely-actions/deciles-charts
